### ISSUE TITLE
ProgressDialog keyword argument

### ISSUE THREAD

**Issue by berl** [AllenInstitute/ccfviewer#1]
Is there a particular version of pyqtgraph that is expected here?  

>python viewer.py
Traceback (most recent call last):
  File "viewer.py", line 18, in <module>
    atlas_data = CCFAtlasData(resolution=resolution)
  File "C:\Users\synbio\Documents\Python_Scripts\ccfviewer\aiccf\data.py", line 45, in __init__
    resolution = self.download_and_cache()
  File "C:\Users\synbio\Documents\Python_Scripts\ccfviewer\aiccf\data.py", line 71, in download_and_cache
    with pg.ProgressDialog("Preparing %dum CCF data" % resolution, maximum=6, nested=True) as dlg:
TypeError: __init__() got an unexpected keyword argument 'nested'

My conda environment is
certifi:        2016.2.28-py27_0
    h5py:           2.7.0-np113py27_0
    hdf5:           1.8.15.1-vc9_4
    jpeg:           8d-vc9_2
    libpng:         1.6.30-vc9_1
    libtiff:        4.0.6-vc9_2
    mkl:            2017.0.3-0
    numpy:          1.13.1-py27_0
    openssl:        1.0.2l-vc9_0
    pip:            9.0.1-py27_1
    pyqt:           4.11.4-py27_7
    pyqtgraph:      0.10.0-py27_0
    python:         2.7.13-1
    qt:             4.8.7-vc9_9
    setuptools:     36.4.0-py27_1
    sip:            4.18-py27_0
    six:            1.10.0-py27_0
    vc:             9-0
    vs2008_runtime: 9.00.30729.5054-0
    wheel:          0.29.0-py27_0
    wincertstore:   0.2-py27_0
    zlib:           1.2.11-vc9_0

plus pip install pynrrd

getting rid of the offending keyword gets me to another error, but I figure there's some underlying dependency that would fix all this

**Comment by campagnola** [comment]
Yes, you need the latest  version from github. This should do it for you:

    pip install git+https://github.com/pyqtgraph/pyqtgraph

**Comment by campagnola** [comment]
README has been updated.
